source-file ~/.config/tmux/colors.conf

set -g default-terminal "alacritty"
set -as terminal-features ',alacritty:RGB'

set -g mouse on

unbind C-b
set -g prefix C-a
bind C-a send-prefix

# Open a new window using 't'
bind t new-window -c "#{pane_current_path}"

bind | split-window -h -c "#{pane_current_path}"
bind - split-window -v -c "#{pane_current_path}"

# bind -r h select-pane -L
# bind -r j select-pane -D
# bind -r k select-pane -U
# bind -r l select-pane -R

bind h split-window -hb -c "#{pane_current_path}"
bind j split-window -v  -c "#{pane_current_path}"
bind k split-window -vb -c "#{pane_current_path}"
bind l split-window -h  -c "#{pane_current_path}"

bind -r Left if -F '#{pane_at_left}'   'previous-window' 'select-pane -L'
bind -r Right if -F '#{pane_at_right}'  'next-window'     'select-pane -R'
bind -r Up select-pane -U
bind -r Down select-pane -D

bind q kill-session

bind R command-prompt -I "#{window_name}" "rename-window '%%'"
bind r command-prompt -I "#{session_name}" "rename-session '%%'"

#status bar
set -g status-position bottom
set -g status-style bg=default

set -g status on
set -g status-right "#[fg=#{@thm_primary},bold] #S "

set -g status-left ""
# set -g window-status-format "#[fg=color8,bg=default]#I:#[fg=color8,bg=default]#W"
# set -g window-status-current-format "#[fg=color15,bg=default]#I:#[fg=color8,bg=default]#W"
set -g window-status-format "#[fg=#{@thm_outline},,bg=default]#I:#W"
set -g window-status-current-format "#[fg=#{@thm_primary},bg=default,bold]#I:#W"

set -g pane-border-style fg="#{@thm_surface_variant}"
set -g pane-active-border-style fg="#{@thm_primary}"

bind C-r source-file ~/.tmux.conf \; display "Config Reloaded!"


set -g @plugin 'tmux-plugins/tpm'
set -g @plugin 'tmux-plugins/tmux-sensible'
set -g @plugin 'tmux-plugins/tmux-resurrect'
set -g @plugin 'tmux-plugins/tmux-continuum'

set -g @resurrect-capture-pane-contents "on"
# set -g @continuum-restore "on"

set -g @resurrect-dir '~/.tmux/resurrect' 
#
# run '~/.tmux/plugins/tpm/tpm'
run '~/.tmux/plugins/tpm/tpm'
